apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb-rbua
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb-rbua
    app.kubernetes.io/part-of: mongo
  name: mongodb-rbua
  namespace: sde-rcook-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: mongodb-rbua
status:
  loadBalancer: {}
